#!/bin/bash 

##### Information 
# Project name : Ai shuree
# Founder : Shuree  
# Worker : USPM [buya.psh@gmail.com]  
# Code writer : B.Sukhbat [1998bsuhe@gmail.com]  
# Used language : Linux bash script  

##### Setup up useful file and global variable 
# temp file 
tmp=/tmp/tmp_file_$$
# first level file name sort index
echo {a..z}{a..z}{a..z} > /tmp/lineindex 
# level abc parser user 26 alphabet
echo {a..z} > /tmp/abcindex 
# current directory
parser='./'
# input file stored directory
uploads=$parser/uploads

##### Setup useful functions
source './functions'

##### Check input file is html or pdf 
if [ $(echo $1 | awk -F '.' '{print $NF}') == 'pdf' ] ;then 
    echo pdf 
    pdftotext -layout -nopgbrk "$uploads/$1" ${tmp}_coverted_data

    # remove empty line  
    cat ${tmp}_coverted_data | awk 'NF!=0' > ${tmp}_coverted_data_tmp

	# pdf_cleaning $tmp_coverted_data > $tmp_cleaned_data
    while read -r line; do echo $line; done < ${tmp}_coverted_data_tmp > ${tmp}_cleaned_data 

    # Setup file body range (now manually ==> change to auto)
    # Body first line number
    # first_range=0
    first_range=392
    # Body end line number 
    # second_range=$(awk 'END {print NR}' < ${tmp}_cleaned_data)
    second_range=4943

    # Divide body   
    cat ${tmp}_cleaned_data | awk ''$first_range' < NR && NR < '$second_range'' > ${tmp}_cleaned_data-temp || exit 1
    mv ${tmp}_cleaned_data-temp ${tmp}_cleaned_data
else 
    if [[ $(echo $1 | awk '{if($0~/^http/){print "true"}else{print "false"}}') == 'true' ]];then 
        python3 './python/html2pdf.py' ''$1'' "${tmp}-html-to-pdf file"
        pdftotext -layout -nopgbrk "${tmp}-html-to-pdf file" ${tmp}_coverted_data
        cat ${tmp}_coverted_data | awk 'NF!=0' > ${tmp}_coverted_data_tmp
        while read -r line; do echo $line; done < ${tmp}_coverted_data_tmp > ${tmp}_cleaned_data 
        # Body first line number
        first_range=0
        # first_range=392
        # Body end line number 
        second_range=$(awk 'END {print NR}' < ${tmp}_cleaned_data)
        # second_range=4943

        # Divide body   
        cat ${tmp}_cleaned_data | awk ''$first_range' < NR && NR < '$second_range'' > ${tmp}_cleaned_data-temp || exit 1
        mv ${tmp}_cleaned_data-temp ${tmp}_cleaned_data
    fi 
fi

##### Make directory, store text file 
# make directory
mkdir $parser/result-0
# Copy cleaned data to tmp directory 
cp ${tmp}_cleaned_data $parser/result-0

##### Loop by parsing level 
# Setup level count 
count=0
for main_word in $(echo $2)
do
    # Create result storing directory 
	mkdir $parser/result-$(($count + 1))
    # Read all input files 
	files=$(find $parser/result-${count} -type f | sort)
    # Store level type into check variable 
    levelType=$(echo $main_word | awk -F "@" '{print $NF}')  
    # Store level key word into word variable 
    word=$(echo $main_word | awk -F '@' '{$NF="";print}' | sed 's/ /@/g')
    # Check level type 
    if [ $levelType == 'ug' ];then 
        # Loop by file 
        for file in $(echo $files)
        do 
            # Create directory for store this level result
            createDirectory "$count" "$file"
            # Search part
            cat $file | 
            grep -n ''$(seach_word_abc $(echo $word | sed 's/@/ /g'))'' | 
            sed 's/ /_/g' | 
            awk -F ':' '{print $2,$1,$1-1}' > ${tmp}-search-result-v1
            # Check first level or not
            setupFilenameIndex "$count" "${tmp}-search-result-v1" > ${tmp}-search-result-v2
            # Prepare search result
            prepareSearchResult "${tmp}-search-result-v2" "$file" > ${tmp}-search-result-v3
            # Divide file by search result
            divideFile "${tmp}-search-result-v3"
        done
    elif [ $levelType == 'abc' ];then 
        # Loop by all files
        for file in $(echo $files)
        do
            # Create directory for store this level result
            createDirectory "$count" "$file"
            # Search word index preparation
                # store user input to user_input_search_word variable
                user_input_search_word=$(echo $word | awk -F "@" '{print $1}')
                # take alphabet from user input
                alphabet=$(echo $user_input_search_word | awk '{abc=""; for(i=1;i<=length($0);i++){if(substr($0,i,1) ~ /[a-z]/){abc=abc""substr($0,i,1)}};print abc}')
                # find user input alphabet index ==> I need 1 to this index loop
                alphabet_index=$(cat /tmp/abcindex | sed 's/ /\n/g' | grep -n "$alphabet" | awk -F ":" '{print $1}')
            # Setup every file abc number 
            sed_number=1
            while true 
            do 
                # Search part 
                # store seach target abc 
                search_abc=$(cat /tmp/abcindex | awk '{print $'$sed_number'}')
                # change user input to first abc 
                search_word=$(echo $user_input_search_word | sed 's/[a-z]/'$search_abc'/g')
                cat $file | 
                grep -n ''^$search_word'\| '$search_word' ' | head -1 > ${tmp}-search-result-v1
                # Setup loop stop case variable 
                result=$(cat ${tmp}-search-result-v1  | awk 'END{print NR}')
                # Check loop stop
                if [ $result -eq 0 ];then 
                    # Check divide result or copy result
                    if [[ -s ${tmp}-search-result-v1-collect ]];then
                        cat ${tmp}-search-result-v1-collect | awk -F ':' '{print $NF,$1,$1-1}' > ${tmp}-search-result-v2
                        # Prepare search result
                        prepareSearchResult "${tmp}-search-result-v2" "$file" > ${tmp}-search-result-v3 
                        # Divide file by search result
                        divideFile "${tmp}-search-result-v3"
                    else 
                        # Directly copy result file
                        cat $file > $parser/result-$(($count + 1))/$(echo $file | awk -F "/" '{$1=""; $2=""; $3="";print $0}' | xargs echo | sed 's/ /\//g')/"@@@" 
                    fi 
                    rm -rf ${tmp}-search-result-v1-collect
                    break 
                else 
                    # Collect search result
                    cat ${tmp}-search-result-v1 | awk '{print $0":'$search_abc'"}' >> ${tmp}-search-result-v1-collect
                fi 
                # increase sub number
                sed_number=$(($sed_number + 1))
            done  
        done 
    elif [ $levelType == 'roman' ];then 
        for file in $(echo $files)
        do
            # Create directory for store this level result
            createDirectory "$count" "$file"
            # user input 
            user_input_search_word=$(echo $word | awk -F "@" '{print $1}')
            # Search roman number from file and 
            #   if result is founded search next roman number 
            #   or result is not founded stop searching
            search_roman_number=1
            while true 
            do
                # Search part
                cat $file | 
                grep -nx ''$user_input_search_word" "$(int2roman $search_roman_number)'' | 
                # grep -nx ''$(echo $word | sed 's/@/ /g' | awk '{print $1}')" "$(int2roman $search_roman_number)'\|'$(echo $word | 
                # sed 's/@/ /g' | 
                # awk '{print $1}')" "$(int2roman $search_roman_number)"[A-Z]"' \|^\['$(echo $word | sed 's/@/ /g' | 
                # awk '{print $1}')" "$(int2roman $search_roman_number)"[A-Z]"'' | 
                sed 's/ /_/g' > ${tmp}-search-result-v1 
                # Setup loop stop case variable 
                result=$(cat ${tmp}-search-result-v1 | awk 'END {print NR}')
                # Check loop stop
                if [[ $result == 0 ]];then 
                    cat ${tmp}-search-result-v1-collect | awk -F ':' '{print $NF,$1,$1-1}' > ${tmp}-search-result-v2
                    # Check first level or not
                    setupFilenameIndex "$count" "${tmp}-search-result-v2" > ${tmp}-search-result-v3
                    # Prepare search result
                    prepareSearchResult "${tmp}-search-result-v3" "$file" > ${tmp}-search-result-v4 
                    # Divide file by search result
                    divideFile "${tmp}-search-result-v4"
                    # Remove first search result 
                    rm -rf ${tmp}-search-result-v1-collect 
                    break
                else 
                    # Collect search result
                    cat ${tmp}-search-result-v1 >> ${tmp}-search-result-v1-collect
                fi 
                # increase roman number
                search_roman_number=$(($search_roman_number + 1))
            done 
        done 
    elif [ $levelType == 'range' ];then 
        sed_number=1
        for file in $(echo $files)
        do
            # Create directory for store this level result
            createDirectory "$count" "$file"
            # Search roman number from file and 
            #   if result is founded search next roman number 
            #   or result is not founded stop searching
            while true 
            do
                # Search part 
                # setup search word
                search_number=$(echo $word | awk -F '@' '{print $1}' | sed 's/1/'$sed_number'/g')
                # search word
                cat $file | grep -n '^'$search_number' \| '$search_number' ' > ${tmp}-search-result-v1
                # Setup loop stop case variable 
                result=$(cat ${tmp}-search-result-v1 | awk 'END{print NR}')
                # Check loop stop
                if [ $result == 0 ];then
                    cat ${tmp}-search-result-v1-collect | awk -F ':' '{print $NF,$1,$1-1}' > ${tmp}-search-result-v2
                    # Check first level or not
                    setupFilenameIndex "$count" "${tmp}-search-result-v2" > ${tmp}-search-result-v3
                    # Prepare search result
                    prepareSearchResult "${tmp}-search-result-v3" "$file" > ${tmp}-search-result-v4 
                    # Divide file by search result
                    divideFile "${tmp}-search-result-v4"
                    # Remove first search result 
                    rm -rf ${tmp}-search-result-v1-collect 
                    break
                else 
                    # Collect search result
                    cat ${tmp}-search-result-v1 | awk '{print $0,":'$sed_number'"}' >> ${tmp}-search-result-v1-collect 
                fi 
                # increase range number
                sed_number=$(($sed_number + 1))
            done 
        done 
    elif [ $levelType == 'inRange' ];then 
        for file in $(echo $files)
        do
            # Create directory for store this level result
            createDirectory "$count" "$file"
            # Search roman number from file and 
            #   if result is founded search next roman number 
            #   or result is not founded stop searching
            sed_number=1
            while true 
            do
                # Search part 
                # setup search word
                search_number=$(echo $word | awk -F '@' '{print $1}' | sed 's/1/'$sed_number'/g')
                # search word
                cat $file | grep -n '^'$search_number' \| '$search_number' ' > ${tmp}-search-result-v1
                # Setup loop stop case variable 
                result=$(cat ${tmp}-search-result-v1 | awk 'END{print NR}')
                # Check loop stop
                if [ $result == 0 ];then
                    # Check divide result or copy result
                    if [[ -s ${tmp}-search-result-v1-collect ]];then
                        cat ${tmp}-search-result-v1-collect | awk -F ':' '{print $NF,$1,$1-1}' > ${tmp}-search-result-v2
                        # Prepare search result
                        prepareSearchResult "${tmp}-search-result-v2" "$file" > ${tmp}-search-result-v3 
                        # Divide file by search result
                        divideFile "${tmp}-search-result-v3"
                    else 
                        # Directly copy result file
                        cat $file > $parser/result-$(($count + 1))/$(echo $file | awk -F "/" '{$1=""; $2=""; $3="";print $0}' | xargs echo | sed 's/ /\//g')/"@@@" 
                    fi 
                    rm -rf ${tmp}-search-result-v1-collect
                    break 
                else 
                    # Collect search result
                    cat ${tmp}-search-result-v1 | awk '{print $0,":'$sed_number'"}' >> ${tmp}-search-result-v1-collect 
                fi 
                # increase range number
                sed_number=$(($sed_number + 1))
            done 
        done 
    elif [ $levelType == 'sub' ];then 
        for file in $(echo $files)
        do
            # Create directory for store this level result
            createDirectory "$count" "$file"
            # Setup every file sub number
            sed_number=1
            while true 
            do 
                # Search part 
                search_number=$(echo $word | awk -F "@" '{print $1}' | sed 's/1/'${sed_number}'/g' )
                cat $file | 
                grep -n '^'$search_number'\| '$search_number' ' | head -1 > ${tmp}-search-result-v1 
                # Setup loop stop case variable 
                result=$(cat ${tmp}-search-result-v1  | awk 'END{print NR}')
                # Check loop stop
                if [ $result -eq 0 ];then 
                    # Check divide result or copy result
                    if [[ -s ${tmp}-search-result-v1-collect ]];then
                        cat ${tmp}-search-result-v1-collect | awk -F ':' '{print $NF,$1,$1-1}' > ${tmp}-search-result-v2
                        # Prepare search result
                        prepareSearchResult "${tmp}-search-result-v2" "$file" > ${tmp}-search-result-v3 
                        # Divide file by search result
                        divideFile "${tmp}-search-result-v3"
                    else 
                        # Directly copy result file
                        cat $file > $parser/result-$(($count + 1))/$(echo $file | awk -F "/" '{$1=""; $2=""; $3="";print $0}' | xargs echo | sed 's/ /\//g')/"@@@" 
                    fi 
                    rm -rf ${tmp}-search-result-v1-collect
                    break 
                else 
                    # Collect search result
                    cat ${tmp}-search-result-v1 | awk '{print $0":'$sed_number'"}' >> ${tmp}-search-result-v1-collect
                fi 
                # increase sub number
                sed_number=$(($sed_number + 1))
            done  
        done 
    elif [ $levelType == 'lroman' ];then
        # Loop by all files
        for file in $(echo $files)
        do
            # Create directory for store this level result
            createDirectory "$count" "$file"
            # store user input to user_input_search_word variable
            user_input_search_word=$(echo $word | awk -F "@" '{print $1}')
            # Setup every file abc number 
            sed_number=1
            while true 
            do 
                # Search part 
                # store seach target abc 
                search_lroman=$(int2roman $sed_number | tr '[:upper:]' '[:lower:]')
                # change user input to first abc 
                search_word=$(echo $user_input_search_word | sed 's/[a-z]/'$search_lroman'/g')
                cat $file | 
                grep -n ''^$search_word'\| '$search_word' ' | head -1 > ${tmp}-search-result-v1
                # Setup loop stop case variable 
                result=$(cat ${tmp}-search-result-v1  | awk 'END{print NR}')
                # Check loop stop
                if [ $result -eq 0 ];then 
                    # Check divide result or copy result
                    if [[ -s ${tmp}-search-result-v1-collect ]];then
                        cat ${tmp}-search-result-v1-collect | awk -F ':' '{print $NF,$1,$1-1}' > ${tmp}-search-result-v2
                        # Prepare search result
                        prepareSearchResult "${tmp}-search-result-v2" "$file" > ${tmp}-search-result-v3 
                        # Divide file by search result
                        divideFile "${tmp}-search-result-v3"
                    else 
                        # Directly copy result file
                        cat $file > $parser/result-$(($count + 1))/$(echo $file | awk -F "/" '{$1=""; $2=""; $3="";print $0}' | xargs echo | sed 's/ /\//g')/"@@@" 
                    fi 
                    rm -rf ${tmp}-search-result-v1-collect
                    break 
                else 
                    # Collect search result
                    cat ${tmp}-search-result-v1 | awk '{print $0":'$search_lroman'"}' >> ${tmp}-search-result-v1-collect
                fi 
                # increase sub number
                sed_number=$(($sed_number + 1))
            done  
        done 
    elif [ $levelType == 'onlyRoman' ];then
        sed_number=1
        for file in $(echo $files)
        do
            # Create directory for store this level result
            createDirectory "$count" "$file"
            # user input 
            user_input_search_word=$(echo $word | awk -F "@" '{print $1}')
            # Search roman number from file and 
            #   if result is founded search next roman number 
            #   or result is not founded stop searching
            while true 
            do
                # Search part 
                # setup search word
                search_number=$(int2roman $sed_number)
                # search word
                search_word=$(echo $user_input_search_word | sed 's/[A-Z]/'$search_number'/g')
                cat $file | grep -n '^'$search_word'' > ${tmp}-search-result-v1
                # Setup loop stop case variable 
                result=$(cat ${tmp}-search-result-v1 | awk 'END{print NR}')
                # Check loop stop
                if [ $result == 0 ];then
                    cat ${tmp}-search-result-v1-collect | awk -F ':' '{print $NF,$1,$1-1}' > ${tmp}-search-result-v2
                    # Check first level or not
                    setupFilenameIndex "$count" "${tmp}-search-result-v2" > ${tmp}-search-result-v3
                    # Prepare search result
                    prepareSearchResult "${tmp}-search-result-v3" "$file" > ${tmp}-search-result-v4 
                    # Divide file by search result
                    divideFile "${tmp}-search-result-v4"
                    # Remove first search result 
                    rm -rf ${tmp}-search-result-v1-collect 
                    break
                else 
                    # Collect search result
                    cat ${tmp}-search-result-v1 | awk '{print $0,":'$search_number'"}' >> ${tmp}-search-result-v1-collect 
                fi 
                # increase range number
                sed_number=$(($sed_number + 1))
            done 
        done 
    elif [ $levelType == 'numberBlvl' ];then
        # Loop by all files
        for file in $(echo $files)
        do
            # Create directory for store this level result
            createDirectory "$count" "$file"
            # Search word before number setup
            if [[ $(echo $file | awk -F '/' '{print $NF}' | awk '{if($0 ~/^[a-z]/){print "true"} else {print "false"}}') == 'true' ]];then 
                search_half_word=$(echo $file | awk -F "<sep_index>" '{print $2}')
            else 
                search_half_word=$(echo $file | xargs basename)
            fi 

            sed_number=1
            while true 
            do 
                # Search part 
                # change user input to first abc 
                search_word=$(echo "$search_half_word\.$sed_number")
                cat $file | 
                grep -n ''^$search_word'\| '$search_word' ' | head -1 > ${tmp}-search-result-v1
                # Setup loop stop case variable 
                result=$(cat ${tmp}-search-result-v1  | awk 'END{print NR}')
                # Check loop stop
                if [ $result -eq 0 ];then 
                    # Check divide result or copy result
                    if [[ -s ${tmp}-search-result-v1-collect ]];then
                        cat ${tmp}-search-result-v1-collect | awk -F ':' '{print $NF,$1,$1-1}' > ${tmp}-search-result-v2
                        # Prepare search result
                        prepareSearchResult "${tmp}-search-result-v2" "$file" > ${tmp}-search-result-v3 
                        # Divide file by search result
                        divideFile "${tmp}-search-result-v3"
                    else 
                        # Directly copy result file
                        cat $file > $parser/result-$(($count + 1))/$(echo $file | awk -F "/" '{$1=""; $2=""; $3="";print $0}' | xargs echo | sed 's/ /\//g')/"@@@" 
                    fi 
                    rm -rf ${tmp}-search-result-v1-collect
                    break 
                else 
                    # Collect search result
                    cat ${tmp}-search-result-v1 | awk '{print $0":'$sed_number'"}' >> ${tmp}-search-result-v1-collect
                fi 
                # increase sub number
                sed_number=$(($sed_number + 1))
            done  
        done 
    fi 
    # Increase level number
	count=$(($count + 1))
done 

##### Result convert to csv
for csv_row in $(find $(echo $parser/result* | sed 's/ /\n/g' | tail -1) -type f | sort) ; do echo $(echo $csv_row | awk -F '/' '{$1="";$2="";print $0}' | awk -F '<sep_index>' '{print $2}' | sed 's/ /\",\"/g' | sed 's/^/\"/g' | sed 's/$/\"/g')',"'$(cat $csv_row)'"'  ;done > $parser/final-$$.csv

##### Print result csv file name
echo '{ "output": "final-'$$'.csv"}'

##### Clean temp file and directory
rm -rf ${tmp}*
# Remove comment in production version !!!
# rm -rf $parser/result-*